/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/Button/BaseButton.vue')['default']
    CircleAvatar: typeof import('./src/components/Avatar/CircleAvatar.vue')['default']
    ClassificationCard: typeof import('./src/components/Classification/ClassificationCard.vue')['default']
    ClassificationChip: typeof import('./src/components/Chip/ClassificationChip.vue')['default']
    Collapse: typeof import('./src/components/collapse/Collapse.vue')['default']
    ConfirmModal: typeof import('./src/components/Modal/ConfirmModal.vue')['default']
    EmojiPicker: typeof import('./src/components/Emoji/EmojiPicker.vue')['default']
    FormInput: typeof import('./src/components/Input/FormInput.vue')['default']
    GroupAvatar: typeof import('./src/components/Avatar/GroupAvatar.vue')['default']
    ImageOrVideo: typeof import('./src/components/Media/ImageOrVideo.vue')['default']
    IonAlert: typeof import('@ionic/vue')['IonAlert']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonPopover: typeof import('@ionic/vue')['IonPopover']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    Key: typeof import('./src/components/Key/Key.vue')['default']
    LangDropdown: typeof import('./src/components/Dropdown/LangDropdown.vue')['default']
    LoadingSpinner: typeof import('./src/components/Loading/LoadingSpinner.vue')['default']
    MobileBackButton: typeof import('./src/components/Button/MobileBackButton.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    PaginationTable: typeof import('./src/components/Table/PaginationTable.vue')['default']
    ProfileUI: typeof import('./src/components/Sidebar/components/ProfileUI.vue')['default']
    QrCode: typeof import('./src/components/QrCode/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsUI: typeof import('./src/components/Sidebar/components/SettingsUI.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    ThemeToggle: typeof import('./src/components/Toggle/ThemeToggle.vue')['default']
  }
}
