/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/Button/BaseButton.vue')['default']
    CircleAvatar: typeof import('./src/components/Avatar/CircleAvatar.vue')['default']
    ConfirmModal: typeof import('./src/components/Modal/ConfirmModal.vue')['default']
    CoverAvatar: typeof import('./src/components/Profile/CoverAvatar.vue')['default']
    FormInput: typeof import('./src/components/Input/FormInput.vue')['default']
    IonAlert: typeof import('@ionic/vue')['IonAlert']
    IonAvatar: typeof import('@ionic/vue')['IonAvatar']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonModal: typeof import('@ionic/vue')['IonModal']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    LangDropdown: typeof import('./src/components/Dropdown/LangDropdown.vue')['default']
    LoadingSpinner: typeof import('./src/components/Loading/LoadingSpinner.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    PaginationTable: typeof import('./src/components/Table/PaginationTable.vue')['default']
    ProfileUI: typeof import('./src/components/Sidebar/components/ProfileUI.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsUI: typeof import('./src/components/Sidebar/components/SettingsUI.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    ThemeToggle: typeof import('./src/components/Toggle/ThemeToggle.vue')['default']
  }
}
