/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/Admin/Header/AdminHeader.vue')['default']
    AdminSidebar: typeof import('./src/components/Admin/Sidebar/AdminSidebar.vue')['default']
    AOHeader: typeof import('./src/components/OA/Header/AOHeader.vue')['default']
    AvatarModal: typeof import('./src/components/Shared/Avatar/AvatarModal.vue')['default']
    BackButton: typeof import('./src/components/Shared/Button/BackButton.vue')['default']
    BaseButton: typeof import('./src/components/Shared/Button/BaseButton.vue')['default']
    CircleAvatar: typeof import('./src/components/Shared/Avatar/CircleAvatar.vue')['default']
    ClassificationCard: typeof import('./src/components/Shared/Classification/ClassificationCard.vue')['default']
    ClassificationChip: typeof import('./src/components/Shared/Chip/ClassificationChip.vue')['default']
    Collapse: typeof import('./src/components/Shared/collapse/Collapse.vue')['default']
    ConfirmModal: typeof import('./src/components/Shared/Modal/ConfirmModal.vue')['default']
    DateInput: typeof import('./src/components/Shared/DatePicker/DateInput.vue')['default']
    DateRangePicker: typeof import('./src/components/Shared/DatePicker/DateRangePicker.vue')['default']
    EmojiPicker: typeof import('./src/components/Shared/Emoji/EmojiPicker.vue')['default']
    FormInput: typeof import('./src/components/Shared/Input/FormInput.vue')['default']
    GroupAvatar: typeof import('./src/components/Shared/Avatar/GroupAvatar.vue')['default']
    ImageOrVideo: typeof import('./src/components/Shared/Media/ImageOrVideo.vue')['default']
    IonAlert: typeof import('@ionic/vue')['IonAlert']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonList: typeof import('@ionic/vue')['IonList']
    IonModal: typeof import('@ionic/vue')['IonModal']
    IonPopover: typeof import('@ionic/vue')['IonPopover']
    IonSearchbar: typeof import('@ionic/vue')['IonSearchbar']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    Key: typeof import('./src/components/Shared/Key/Key.vue')['default']
    LangDropdown: typeof import('./src/components/Shared/Dropdown/LangDropdown.vue')['default']
    LoadingSpinner: typeof import('./src/components/Shared/Loading/LoadingSpinner.vue')['default']
    MobileBackButton: typeof import('./src/components/Shared/Button/MobileBackButton.vue')['default']
    Modal: typeof import('./src/components/Shared/Modal/Modal.vue')['default']
    OAHeader: typeof import('./src/components/OA/Header/OAHeader.vue')['default']
    OAPageHeader: typeof import('./src/components/OA/Header/OAPageHeader.vue')['default']
    OASidebar: typeof import('./src/components/OA/Sidebar/OASidebar.vue')['default']
    PaginationTable: typeof import('./src/components/Shared/Table/PaginationTable.vue')['default']
    PopoverButton: typeof import('./src/components/Shared/Dropdown/PopoverButton.vue')['default']
    ProfileUI: typeof import('./src/components/App/Sidebar/components/ProfileUI.vue')['default']
    QrCode: typeof import('./src/components/Shared/QrCode/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Shared/Search/Search.vue')['default']
    SettingsUI: typeof import('./src/components/App/Sidebar/components/SettingsUI.vue')['default']
    Sidebar: typeof import('./src/components/App/Sidebar/Sidebar.vue')['default']
    Switch: typeof import('./src/components/Shared/Switch/Switch.vue')['default']
    ThemeToggle: typeof import('./src/components/Shared/Toggle/ThemeToggle.vue')['default']
    ZaloSticker: typeof import('./src/components/Shared/Sticker/Zalo/ZaloSticker.vue')['default']
    ZaloStickerGrid: typeof import('./src/components/Shared/Sticker/Zalo/ZaloStickerGrid.vue')['default']
    ZaloStickerPackBar: typeof import('./src/components/Shared/Sticker/Zalo/ZaloStickerPackBar.vue')['default']
    ZaloStickerPicker: typeof import('./src/components/Shared/Sticker/Zalo/ZaloStickerPicker.vue')['default']
    ZaloStickerPreview: typeof import('./src/components/Shared/Sticker/Zalo/ZaloStickerPreview.vue')['default']
  }
}
